// ********RoostGPT********
// Test generated by RoostGPT for test Csharp-beginner using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
using System.Windows.Controls;
using NUnit.Framework;
using TicTacToe;
using NSubstitute;

namespace TicTacToe.Test
{
    [TestFixture]
    public class ButtonTileMapping_e3d45d6710
    {
        // TODO: Adjust the test cases to match your specific context and requirements.

        [Test]
        public void Constructor_ValidParameters_ShouldSetProperties()
        {
            // Arrange
            var button = Substitute.For<Button>();
            int tileX = 0;
            int tileY = 0;

            // Act
            var mapping = new ButtonTileMapping(button, tileX, tileY);

            // Assert
            Assert.That(mapping.Button, Is.EqualTo(button));
            Assert.That(mapping.TileX, Is.EqualTo(tileX));
            Assert.That(mapping.TileY, Is.EqualTo(tileY));
        }

        [Test]
        public void Constructor_NegativeTileCoordinates_ShouldSetProperties()
        {
            // Arrange
            var button = Substitute.For<Button>();
            int tileX = -1;
            int tileY = -1;

            // Act
            var mapping = new ButtonTileMapping(button, tileX, tileY);

            // Assert
            Assert.That(mapping.Button, Is.EqualTo(button));
            Assert.That(mapping.TileX, Is.EqualTo(tileX));
            Assert.That(mapping.TileY, Is.EqualTo(tileY));
        }

        // Additional tests could include passing null for the button parameter,
        // extremely high or low tile coordinates, etc.
    }
}

