// ********RoostGPT********
// Test generated by RoostGPT for test Csharp-beginner using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
using NUnit.Framework;
using TicTacToe;
using System;

namespace TicTacToe.Test
{
    [TestFixture]
    public class PlayerEventArgs_baeff9d6c5
    {
        private Player _player;
        private PlayerEventArgs _playerEventArgs;

        [SetUp]
        public void Setup()
        {
            // TODO: Initialize _player with a suitable Player object before running tests
            _player = new Player("TestPlayer", PlayerSymbol.X);
            _playerEventArgs = new PlayerEventArgs(_player);
        }

        [Test]
        public void Constructor_ValidPlayer_SetsPlayerProperty()
        {
            // Act
            var playerEventArgs = new PlayerEventArgs(_player);

            // Assert
            Assert.AreEqual(_player, playerEventArgs.Player, "Constructor should set the Player property.");
        }

        [Test]
        public void Constructor_NullPlayer_ThrowsArgumentNullException()
        {
            // Act & Assert
            var ex = Assert.Throws<ArgumentNullException>(() => new PlayerEventArgs(null));
            Assert.That(ex.ParamName, Is.EqualTo("player"), "Constructor should throw ArgumentNullException for null Player parameter.");
        }

        // Additional test cases can be added here to cover more edge cases and scenarios
    }
}

